#!/bin/sh

echo "=====================================" > /dev/console
echo "  Hello from Ehab's initramfs!"        > /dev/console
echo "  Feel free to unplug your SD Card"    > /dev/console
echo "=====================================" > /dev/console

